### ISSUE TITLE
[warn] duplicated imports

### ISSUE THREAD

**Issue by ibrunotome** [manchenkoff/nuxt-auth-sanctum#1]
Your article is very good 🎉

Switching from the manual version to your package, I got this warnings:

WARN  Duplicated imports "useSanctumAuth", the one from "/Users/.../node_module… will be ignored
│  WARN  Duplicated imports "useSanctumClient", the one from "/Users/.../node_modu… will be ignored
│  WARN  Duplicated imports "useSanctumUser", the one from "/Users/.../node_module… will be ignored

**Comment by manchenkoff** [comment]
Hey @ibrunotome, thanks 👍 

Could you provide more details on how did you get this error? I tried to install it both in the fresh Nuxt project and one of my previous projects, but couldn't get this message. Both are on the Nuxt 3.7.

Do you have any files in your project with the same name?

**Comment by ibrunotome** [comment]
Sure, Nuxt 3.7 here too. Im using your composables into the api layer and also in the .app

<img width="244" alt="Screenshot 2023-09-25 at 17 05 26" src="https://github.com/manchenkoff/nuxt-auth-sanctum/assets/4256471/97b455c7-9e42-4fd6-81d3-c9016cf18a47">

The only mention of `useSanctumClient` in layers folder (with is outside the .app folder) is in the client plugin in api layer:

```ts
import type { ApiServiceContainer } from '../services/ApiServiceContainer'
import AuthenticationService from '../services/AuthenticationService'
import PasswordService from '../services/PasswordService'
import ProfileService from '../services/ProfileService'
import WorldService from '../services/WorldService'
import AnalysisService from '../services/AnalysisService'

export default defineNuxtPlugin(async (nuxtApp) => {
  const client = useSanctumClient()

  const api: ApiServiceContainer = {
    analysisService: new AnalysisService(client),
    authenticationService: new AuthenticationService(client),
    passwordService: new PasswordService(client),
    profileService: new ProfileService(client),
    worldService: new WorldService(client),
  }

  return { provide: { api } }
})
```

The mentions of `useSanctumClient` in may .app directory

<img width="850" alt="Screenshot 2023-09-25 at 17 11 39" src="https://github.com/manchenkoff/nuxt-auth-sanctum/assets/4256471/8134d8b9-f731-44ad-a304-17a01315869f">

The project is using pnpm workspaces

```yaml
packages:
  - .app
  - layers/*
```

**Comment by manchenkoff** [comment]
To be honest, I'm not familiar with pnpm workspaces, but it looks like this issue is not directly related to the package, but to Nuxt - https://github.com/nuxt/nuxt/issues/13528#issuecomment-1723365653, which leads to https://github.com/unjs/unimport/issues/273. Could you please check the suggestions there and get back if something helped?

**Comment by ibrunotome** [comment]
You're right, looks like is 100% related to unjs/unimport so I will close the issue. Thanks for your help.
