### ISSUE TITLE
[Bug] Typescript error when use interceptors

### ISSUE THREAD

**Issue by carlosvaldesweb** [manchenkoff/nuxt-auth-sanctum#107]
**Describe the bug**
'default' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts(7022)

**To Reproduce**
```
  sanctum: {
    interceptors: {
      onRequest: (app: NuxtApp, ctx: FetchContext) => {
        ctx.options.headers = {
          ...ctx.options.headers,
          "Accept-Language": app.$i18n.localeProperties.value.code,
        };
      },
    },
  },
```

**Screenshots**
<img width="709" alt="Captura de pantalla 2024-06-17 a la(s) 11 09 47 a m" src="https://github.com/manchenkoff/nuxt-auth-sanctum/assets/32969705/4df627fa-799f-4e5f-8fcf-efafba832e03">

**Module information**

-   Version: [e.g. 0.4.0]

```typescript
sanctum: {
    baseUrl: process.env.NUXT_PUBLIC_BACKEND_URL, // Laravel API
    endpoints: {
      user: "/user",
    },
    redirect: {
      onLogin: "/tools/summaries",
    },
  },
```

**Comment by manchenkoff** [comment]
Hey @carlosvaldesweb, I did try to reproduce this behavior but I ended up with a different error - **Type '(app: NuxtApp, ctx: FetchContext) => void' is not assignable to type 'SanctumInterceptor'. Type 'void' is not assignable to type 'Promise<void>'.ts(2322)**

After I added `async` modifier, it went away:

```typescript
sanctum: {
  interceptors: {
    onRequest: async (app: NuxtApp, ctx: FetchContext) => {
      ctx.options.headers = {
        ...ctx.options.headers,
        'Accept-Language': app.$i18n.localeProperties.value.code,
      }
    },
  },
},
```

Please, try to modify your example accordingly. Also, ensure you have a `.nuxt/types/sanctum.d.ts` file with augmented Nuxt types.

Here you can find an example of the usage of custom interceptors that do not trigger any error - [Breeze Nuxt Interceptor](https://github.com/manchenkoff/breeze-nuxt/blob/main/app/app.config.ts#L16)

**Comment by manchenkoff** [comment]
Closed due to inactivity, feel free to re-open in case of further issues
