### ISSUE TITLE
[Question] What im doing wrong with mode: "token"

### ISSUE THREAD

**Issue by brocard** [manchenkoff/nuxt-auth-sanctum#124]
my login always return message :  "CSRF token mismatch.", im using `mode : token`.  Missing somthing at config?

**Comment by manchenkoff** [comment]
Hey @brocard, looks like that. When you use token based authentication, your requests should not be handled by CSRF middleware. Make sure that the domain of your Nuxt application is not in the list of stateful domains - `SANCTUM_STATEFUL_DOMAINS`.

**Comment by brocard** [comment]
Thanks just before my question in read the documentation, and now its workking
