### ISSUE TITLE
CSRF token mismatch

### ISSUE THREAD

**Issue by projct1** [manchenkoff/nuxt-auth-sanctum#126]
`Register.vue`:
```js
const sanctumFetch = useSanctumClient()

await sanctumFetch('register', {
  method: 'POST',
  body: {name, email, password, password_confirmation: passwordConfirm}
})
```

`Nuxt.config.ts`:
```js
export default defineNuxtConfig({
  modules: [
    "nuxt-auth-sanctum"
  ],

  sanctum: {
    baseUrl: 'http://gdebar-lk:85'
  },
})
```

My `cors.php`:
```php
return [
    'paths' => ['*'],
    'allowed_methods' => ['*'],
    'allowed_origins' => [env('FRONTEND_URL')],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => [],
    'max_age' => 0,
    'supports_credentials' => true
];
```

My `sanctum.php`:
```php
return [
    'stateful' => explode(
        ',',
        env('SANCTUM_STATEFUL_DOMAINS', sprintf(
            '%s%s%s',
            'localhost,localhost:3000,127.0.0.1,127.0.0.1:8000,::1',
            Sanctum::currentApplicationUrlWithPort(),
            env('FRONTEND_URL') ? ',' . parse_url(env('FRONTEND_URL'), PHP_URL_HOST) : ''
        ))
    ),

    //defaults below
];
```

My `FRONTEND_URL` is `http://localhost:3000` and `SANCTUM_STATEFUL_DOMAINS` does not exists.

Trying to register new user, but got error:
![image](https://github.com/user-attachments/assets/853dc964-c845-4011-bcc4-e062478afd0e)

**Comment by manchenkoff** [comment]
@projct1 when you use CSRF cookie based authentication, then both applications should work on the same domain, either localhost with different ports or actual domain (and API on a subdomain for example). Otherwise, you will keep getting mismatch error. For more details, please check module documentation and official Sanctum docs

**Comment by projct1** [comment]
Thanks dude, its works :)
