### ISSUE TITLE
419 problem

### ISSUE THREAD

**Issue by Jonston** [manchenkoff/nuxt-auth-sanctum#127]
I recently wrote that localhost:3000 does not send cookies, you said that the domains should be the same except for subdomains. So I transferred the sites to the server, but cookies are still not sent. What could be the reason?!
![image](https://github.com/user-attachments/assets/40dcaff2-30c0-4815-80ac-8c8955e6921f)
![image](https://github.com/user-attachments/assets/0115d05c-94ba-47f4-b8f8-5c26911029cb)
I forgot to clarify. I'm talking about csrf-token cookies

**Comment by Jonston** [comment]
Any ideas?

**Comment by manchenkoff** [comment]
Hey @Jonston, sure, you have to configure `SESSION_DOMAIN` to be `.carpot.cx.ua` to make it work.

![349066567-0115d05c-94ba-47f4-b8f8-5c26911029cb](https://github.com/user-attachments/assets/562f8ade-1bae-4f68-8887-271990533202)

**Comment by marcha** [comment]
I have the same issue in production environment.. Locally, with frontend on localhost:3000 and API on localhost:201 everything is OK,  but  in production where Laravel API is on  sso.dmx.rs and frontend app on kat.dmx.rs it doesn't  work.
My .env settings for Laravel app in production is:
```
APP_URL=https://sso.dmx.rs
FRONTEND_URL=https://kat.dmx.rs
SANCTUM_STATEFUL_DOMAINS=kat.dmx.rs
SESSION_DOMAIN=.dmx.rs

![image](https://github.com/user-attachments/assets/b787b5ce-6193-4967-9fa3-9ecbe085ce38)

**Comment by manchenkoff** [comment]
@marcha if you see cookies set on subdomains, them Laravel is not configured properly. However, SESSION_DOMAIN looks right, so try to reload Laravel config cache, clear the cookies in the browser and restart the app. Once you have correct settings, you will see that Laravel returns cookies only for your TLD.

**Comment by marcha** [comment]
@manchenkoff you were right. I made mistake. I set `session_domain` twice, actually i didn't remove default settings from part where sessions is configured initially. Thank you and sorry for this false alarm.

**Comment by Jonston** [comment]
Thx. I set session_domain and all work well!
