### ISSUE TITLE
[Bug] Can't login with a different user after logout

### ISSUE THREAD

**Issue by LastxTemplar** [manchenkoff/nuxt-auth-sanctum#128]
**Describe the bug**

I have a Nuxt3 project with ssr:false. When logging in with one user, then logging out and try to login again with a different user, it takes two attempts to get logged in, the first one always says unauthenticated.

**To Reproduce**

I recorded a video since there are too many things going on to make a repro, i thought this might be easier to understand:

[Youtube Video](https://youtu.be/30hLLElJnbc)

**Expected behavior**

I expect to be able to successfully login with a different user from the first time.

**Module information**

-   Version: 0.1.2
-   Complete configuration of `sanctum` from your `nuxt.config.ts`

```typescript
export default defineNuxtConfig({
    modules: ['nuxt-auth-sanctum'],

   sanctum: {
    baseUrl: process.env.API_URL, // Laravel API
    origin: process.env.ORIGIN_URL, // Nuxt app, by default will be used 'useRequestURL().origin'
    endpoints: {
      csrf: '/sanctum/csrf-cookie', // CSRF cookie endpoint
      login: '/api/auth/login', // Endpoint that accepts user credentials
      logout: '/api/user/logout', // Endpoint to destroy the current session
      user: '/api/user/me' // Endpoint that return current user information
    },
    redirect: {
      keepRequestedRoute: false, // Keep requested route in the URL for later redirect
      onLogin: '/user/dashboard/account', // Redirect to this page after successful login
      onLogout: '/', // Redirect to this page after successful logout
      onAuthOnly: '/login', // Redirect to this page if user is not authenticated
      onGuestOnly: '/user/dashboard/account' // Redirect to this page if user is authenticated
    }
  },
});
```

**Nuxt environment:**

-   Version: 3.10.3
-   SSR Enabled: no
-   Environment: local

**Laravel environment:**

-   Version: 10.48.16
-   Sanctum installed via Breeze: no
-   [Checklist](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/authentication/spa-cookie#laravel-configuration) completed: yes
-   Session domain from your `config/session.php`: .ziqe.test
-   List of stateful domains from your `config/sanctum.php`

```env
SANCTUM_STATEFUL_DOMAINS=ziqe.test:3000,api.ziqe.test:3000
```

-   CORS settings from your `config/cors.php`

```php
return [
    'paths' => ['api/*', 'sanctum/csrf-cookie'],
    'allowed_methods' => ['*'],
    'allowed_origins' => ['*'],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => [],
    'max_age' => 0,
    'supports_credentials' => true,
];
```

**Comment by LastxTemplar** [comment]
Thank you so much :)

**Comment by manchenkoff** [comment]
Hey @LastxTemplar, unfortunately, I couldn't reproduce the same issue. I used [breeze-nuxt](https://github.com/manchenkoff/breeze-nuxt) template app with disabled SSR and it looks like it works with login/logout for different users from the first time. 

However, I noticed that you have `refreshIdentity()` call after logging out and I assume it might interfere with cookie retrieval after logout since it is not valid anymore. Please, try to remove it and try to reproduce it again. It the issue persists, please try to use breeze-nuxt template with your API to ensure it is a problem in the module and not in your application code.

**Comment by LastxTemplar** [comment]
Thanks for the help, I just switched using web routes instead of api routes for login, logout and register just like in the breeze project, everything seems to be working fine now. As far as I noticed, it works fine when all routes are in the web.php file, moving those routes to api.php breaks for some reason.
