### ISSUE TITLE
[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug.

### ISSUE THREAD

**Issue by GabrielFrohlich** [manchenkoff/nuxt-auth-sanctum#134]
Hello people, im obtaining this error on access /login page

500
[nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`.

<img width="884" alt="image" src="https://github.com/user-attachments/assets/7f508a95-c61a-4360-8e45-e958e94ac28b">

**Comment by manchenkoff** [comment]
Hey @GabrielFrohlich, can you provide a bit more details about the issue? Are you using a breeze-nuxt template or is it your own project? 

From the error it looks like there is an incorrect place for the function call, but I need a code sample to help with solving it.

**Comment by GabrielFrohlich** [comment]
Hello @manchenkoff 

Im using my own project, and it happens every page in the application.

**Comment by manchenkoff** [comment]
@GabrielFrohlich I see, since it is a custom app, can you provide minimal repro where the issue also occurs? Unfortunately, in the fresh install and in the breeze-nuxt it works fine, so we need to reproduce your environment

**Comment by GabrielFrohlich** [comment]
@manchenkoff it was my error, I was calling login direct on script setup.

`const { login } = useSanctumAuth();

const userCredentials = {
    email: 'user@mail.com',
    password: '123123',
};

await login(userCredentials)`
