### ISSUE TITLE
[Question] is it possible to manually update the user object?

### ISSUE THREAD

**Issue by bradley-varol** [manchenkoff/nuxt-auth-sanctum#142]
I would like to be able to update the user object without needing to `refreshIdentity()`, e.g. when doing optimistic UI updates. Is this possible?

Sorry if i've overlooked something obvious here.

**Comment by manchenkoff** [comment]
Hey @bradley-varol, have you tried to use the current user identity object to make the changes?
There is the [useSanctumUser](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/usage/composables/usesantumuser) composable that returns the value written via `useState`, so I assume you can leverage it.

**Comment by bradley-varol** [comment]
Awesome, thank you 🚀
