### ISSUE TITLE
[Question] Is there an method to refresh user based on backend?

### ISSUE THREAD

**Issue by GabrielFrohlich** [manchenkoff/nuxt-auth-sanctum#148]
I wanna refresh user value based on backend values to assure that user has some properties defined. When is the user refreshed by default? Just when the page is refreshed? Is there an existent method to refresh user information based on backend?

**Comment by manchenkoff** [comment]
Hey @GabrielFrohlich, please check the docs of the module [here](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/usage/composables/usesantumauth). By default, users identity is refreshed once you logged in and on page refresh. If you need to manually do that, feel free to use `refreshIdentity` method from composable mentioned in the docs I shared.

**Comment by GabrielFrohlich** [comment]
Nice @manchenkoff 
Thanks for your help!
