### ISSUE TITLE
Accessing the XSRF-TOKEN not working with pusher

### ISSUE THREAD

**Issue by WanyoikeJ** [manchenkoff/nuxt-auth-sanctum#17]
i have this package installed in my nuxt 3 project and its working perfectly, i have this pusher plugin as well that needs to access the XSRF-TOKEN but its not not accessible, any guide on how i can do this. Here is my code:

```
import Echo from 'laravel-echo';
import Pusher from "pusher-js";

window.Pusher = Pusher;

export default defineNuxtPlugin((nuxtApp) => {
    const token = useCookie("XSRF-TOKEN").value;

    Pusher.Runtime.createXHR = () => {
        let xhr = new XMLHttpRequest()
        xhr.withCredentials = true
        return xhr
    }
    
    const echo = new Echo({
      broadcaster: 'pusher',
      key: 'pushingdata',
      wsHost: 'localhost',
      wsPort: 6001,
      wssPort: 443,
      cluster: 'mt1',
      forceTLS: false,
      disableStats: true,
      encrypted: true,
      authEndpoint: 'http://localhost:8000/api/broadcasting/auth',
      auth: {
        headers: {
            'X-Xsrf-Token': token,
        },
      },
      userAuthentication: {
        endpoint: 'http://localhost:8000/api/broadcasting/auth',
        headers: {
            'X-Xsrf-Token': token,
        },
      },
    });

    nuxtApp.vueApp.provide('$echo', echo);
});
```

**Comment by manchenkoff** [comment]
Hey @WanyoikeJ, to be honest, I never tried Pusher and the broadcasting feature in Laravel, but according to [official docs](https://laravel.com/docs/10.x/broadcasting#defining-authorization-routes) it looks like that it handles authentication and authorization on its own, so I would assume that you need to request a CSRF token and pass it to Echo before calling one of these endpoints since it might be not available via `useCookie` when you define the Nuxt plugin. I think [this section](https://laravel.com/docs/10.x/broadcasting#customizing-the-authorization-request) could be useful.

You can take a look at how it is done for other requests [here](https://github.com/manchenkoff/nuxt-auth-sanctum/blob/main/src/runtime/httpFactory.ts#L30).

**Comment by WanyoikeJ** [comment]
Great!!,
Let me look at this is revert if any hiccup comes up.

**Comment by WanyoikeJ** [comment]
Hi @manchenkoff 
i have updates my code to fetch the token in the following format so that i can subscribe to the private channels as well but it seams like the auth header is missing. The response for fetching sactum token brings back null, at the moment. if i subscribe to open channel, it works just fine, but private channels are not working.

```
import Echo from 'laravel-echo'
import Pusher from 'pusher-js'
import { ofetch } from "ofetch";

export default defineNuxtPlugin(() => {
  window.Pusher = Pusher

  const { isAuthenticated } = useSanctumAuth();
  const client = useSanctumClient();
  
  if (isAuthenticated.value) {
    window.Pusher.logToConsole = true;

    window.Echo = new Echo({
      broadcaster: 'pusher',
      key: 'pushingdata',
      wsHost: 'localhost',
      wsPort: 6001,
      wssPort: 443,
      cluster: 'mt1',
      forceTLS: false,
      disableStats: true,
      encrypted: true,
      authorizer: (channel, options) => {
        return {
          authorize: async (socketId, callback) => {
            try {
              const response = client('/sanctum/csrf-cookie');
              console.log(response);
              const res = await client('/api/broadcasting/auth', {
                method: "POST",
                body: {
                  socket_id: socketId,
                  channel_name: channel.name
              }})
  
              callback(null, response)
            } catch (error) {
              callback(error)
            }
          }
        };
      },
    })
  }
})
```

Any ideas on how to get the headers? ive tries `ofetch` but its doing a fresh request so the login session is completely lost at that point

**Comment by WanyoikeJ** [comment]
Worked perfectly @manchenkoff , thanks alot

**Comment by manchenkoff** [comment]
@WanyoikeJ You're welcome, happy to help!

**Comment by ahoiroman** [comment]
May I ask how you solved it, @WanyoikeJ  ? I tried a lot today

**Comment by ahoiroman** [comment]
Hi there,

I just opened https://github.com/manchenkoff/nuxt-auth-sanctum/issues/113. Maybe your solution can help me out, @WanyoikeJ
