### ISSUE TITLE
[Question]  A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`.

### ISSUE THREAD

**Issue by filiptalev** [manchenkoff/nuxt-auth-sanctum#175]
I am having problem with using nuxt-auth-sanctum. I've been using it in other projects and it was working perfectly fine. Today I started new project and it doesn't work. It gives me  A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables` -> this error. 

When i started looking in the node_modules i saw that ./node_modules/nuxt-auth-sanctum/dist/runtime/plugin.js is different my previous projects and this one. Also this error only occures when its mode: "token" mode: "cookie" doesn't give me this error

**Comment by manchenkoff** [comment]
Hey @filiptalev, could you please re-open the issue with `Bug report` template and provide all the requested details in the description accordingly?

**Comment by filiptalev** [comment]
Yes
