### ISSUE TITLE
[Bug] Mode: token recieve nuxt error

### ISSUE THREAD

**Issue by filiptalev** [manchenkoff/nuxt-auth-sanctum#176]
**Describe the bug**

When I try to go to login page it gives me nuxt 500 error like this [nuxt] A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function. This is probably not a Nuxt bug. Find out more at `https://nuxt.com/docs/guide/concepts/auto-imports#vue-and-nuxt-composables`.

at useAppConfig (./node_modules/nuxt/dist/app/config.js:38:41)
at Module.updateAppConfig (./node_modules/nuxt/dist/app/config.js:46:22)
at setupDefaultTokenStorage (./node_modules/nuxt-auth-sanctum/dist/runtime/plugin.js:30:25)
at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
at async ./node_modules/nuxt-auth-sanctum/dist/runtime/plugin.js:68:101
at async setup (./virtual:nuxt:/home/casper/Documents/projects/AlbaniaDanceFederation/albania-dance-federation/cms/.nuxt/plugins/server.mjs:45:116)
at async Object.callAsync (./node_modules/unctx/dist/index.mjs:72:16)
at async applyPlugin (./node_modules/nuxt/dist/app/nuxt.js:146:25)
at async executePlugin (./node_modules/nuxt/dist/app/nuxt.js:183:9)

**To Reproduce**

1. Copy starter pack from minibile theme from theme forest
2. npx nuxi@latest module add nuxt-auth-sanctum
3. Try going to localhost:3000 error shown

**Expected behavior**

Log me in

**Screenshots**

**Module information**

-   Version:  "nuxt-auth-sanctum": "^0.4.13"
-   Complete configuration of `sanctum` from your `nuxt.config.ts`

```typescript
export default defineNuxtConfig({
    modules: ['nuxt-auth-sanctum'],

    sanctum: {
    baseUrl: 'http://localhost:7305/', // Laravel API
    mode: "token",
    userStateKey: 'sanctum.user.identity',
    redirectIfAuthenticated: true,
    redirectIfUnauthenticated: false,
    endpoints: {
      csrf: '/sanctum/csrf-cookie',
      login: '/v1/auth/login',
      logout: '/v1/auth/logout',
      user: '/v1/auth/me'
    },
    csrf: {
      cookie: 'XSRF-TOKEN',
      header: 'X-XSRF-TOKEN',
    },
    client: {
      retry: false,
    },
    redirect: {
      keepRequestedRoute: false,
      onLogin: '/',
      onLogout: '/login',
      onAuthOnly: '/login',
      onGuestOnly: '/',
    },
    globalMiddleware: {
      enabled: false,
      allow404WithoutAuth: true,
    },
    logLevel: 3,
  },,
});
```

**Nuxt environment:**

-   Version: "^3.6.5"
-   SSR Enabled:  no
-   Environment: local 

**Laravel environment:**

-   Version: 11
-   Sanctum installed via Breeze:  no
-   [Checklist](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/authentication/spa-cookie#laravel-configuration) completed: yes 
-   Session domain from your `config/session.php`: `.domain.test` yes
-   List of stateful domains from your `config/sanctum.php`: `['domain.test', 'www.domain.test']` yes
-   CORS settings from your `config/cors.php` yes

```php
return [
    'paths' => ['*'],
    'allowed_methods' => ['*'],
    'allowed_origins' => [
        env('FRONTEND_URL', 'http://localhost:3000'),
    ],
    'allowed_origins_patterns' => [],
    'allowed_headers' => ['*'],
    'exposed_headers' => [],
    'max_age' => 0,
    'supports_credentials' => true,
];
```

**Comment by manchenkoff** [comment]
Hey @filiptalev, I tried to reproduce the behavior but it worked fine without any error.
I noticed that you have the Nuxt version as `3.6.5`, can you try upgrading it to the latest one?
Also, could you provide a code sample of your Vue component/service where you are trying to call the login function of the nuxt-auth-sanctum module?

**Comment by shreejalmaharjan-27** [comment]
+1 I have the same issue, it does not appear to be an issue with nuxt. I had to downgrade the package to `"nuxt-auth-sanctum": "0.4.11"` make it work.

This is how i am calling the login.
```
<template>
    <div v-if="!user" class="p-4 max-w-96">
        <h1 class="text-2xl font-bold mb-4">Login</h1>
        <UInput class="mb-2" v-model="email" placeholder="Email" type="email" />
        <UInput v-model="password" placeholder="Password" type="password" />
        <UButton class="mt-4" @click="click">Login</UButton>
    </div>
</template>

<script setup lang="ts">
import type { User } from '~/types/User';

const currentPage = useState('chat', () => 'chat');

const { login } = useSanctumAuth();
const user = useSanctumUser<User>();

const email = ref('');
const password = ref('');

const toast = useToast()

const click = async () => {
    const creds = {

        "email": email.value,
        "password": password.value
    };
    try {
        await login(creds);
    } catch (error) {
        toast.add({ title: "Invalid credentials", color: "red" });
    }

}
</script>
```

**Comment by manchenkoff** [comment]
Hi @shreejalmaharjan-27, thanks for the code sample, could you also provide `nuxt.config.ts` and your nuxt version?

**Comment by shreejalmaharjan-27** [comment]
> Hi @shreejalmaharjan-27, thanks for the code sample, could you also provide `nuxt.config.ts` and your nuxt version?

My nuxt version is `"nuxt": "^3.13.2",`
Nuxt config
```
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: '2024-04-03',
  devtools: { enabled: true },
  modules: [
    "@nuxt/ui",
    "nuxt-auth-sanctum",
    "@nuxtjs/i18n",
    "@nuxt/content",
    '@nuxt/image',
  ],

  sanctum: {
    baseUrl: 'http://localhost/api', // Laravel API
    endpoints: {
      user: '/user',
    },
    mode: 'token',
  },
  icon: {
    provider: 'server'
  },

  i18n: {
    vueI18n: './i18n.config.ts',
    locales: [
      {
        code: 'en',
        iso: 'en-US',
      },
      {
        code: 'fr',
        iso: 'fr-FR',
      },
      {
        code: 'es',
        iso: 'es-ES',
      },
      {
        code: 'de',
        iso: 'de-DE',
      },
      {
        code: 'pt',
        iso: 'pt-PT',
      },
      {
        code: 'it',
        iso: 'it-IT',
      }
    ],
    defaultLocale: 'en',
  },
})
```

**Comment by manchenkoff** [comment]
@shreejalmaharjan-27 @filiptalev 
I have just published a new version `0.4.14`, please try upgrading and let me know if it helps!

**Comment by shreejalmaharjan-27** [comment]
> @shreejalmaharjan-27 @filiptalev I have just published a new version `0.4.14`, please try upgrading and let me know if it helps!

All good on my side! Thank you for the quick fix

**Comment by filiptalev** [comment]
IT WORKS!!!!!!!!!! I love you people <3 @manchenkoff  @shreejalmaharjan-27

**Comment by filiptalev** [comment]
ITTT WOORKKSSS!!! I LOVE YOU PEOPLE <3 @manchenkoff  @shreejalmaharjan-27
