### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by WanyoikeJ** [manchenkoff/nuxt-auth-sanctum#19]
Hello,

This package is working perfectly but I have not found a way of handling 422 error from the laravel backend, so that I can display them in the client side. here is how am going about it but its not working.

```
async function sendFacebookPost(){
        sending.value = true
        try {
            const {data, error, refresh} = await client(`/api/schedulepost`, {
                method: "POST",
                body: postdata.value,
            });
            console.log(error.response.status);
            sending.value = false
        } catch (error) {
            sending.value = false
            console.log(error);
        }
   }
```

How do I catch these type of errors?

**Comment by manchenkoff** [comment]
Hey @WanyoikeJ, please take a look at #5, I left there an example of `useApiError` composable which might be handy for your case as well

**Comment by WanyoikeJ** [comment]
Thanks @manchenkoff , this worked just fine!!
