### ISSUE TITLE
[Bug] TypeError: undefined is not an object (evaluating 'headers.set')

### ISSUE THREAD

**Issue by ibrunotome** [manchenkoff/nuxt-auth-sanctum#195]
**Describe the bug**

nuxt-auth-sanctum:csr:error Unable to load user identity from API
TypeError: undefined is not an object (evaluating 'headers.set')

**To Reproduce**

Upgraded from 0.4.12 to 0.4.18, tested until v0.4.16 and it works until this version.

**Module information**

-   Version: `0.4.18`
-   Content of your `nuxt.config.ts`:

```typescript
export default defineNuxtConfig({
  modules: [
    '@nuxt/devtools',
    '@nuxt/eslint',
    '@nuxt/fonts',
    '@nuxt/icon',
    '@nuxt/scripts',
    '@nuxtjs/i18n',
    '@nuxtjs/seo',
    '@sentry/nuxt/module',
    'nuxt-auth-sanctum',
  ],

  sanctum: {
    mode: 'cookie',
    baseUrl: 'http://localhost:8000',
    origin: 'http://localhost:3000',
    userStateKey: 'sanctum.user.identity',
    redirectIfAuthenticated: false,
    redirectIfUnauthenticated: false,
    endpoints: {
      csrf: '/sanctum/csrf-cookie',
      login: '/auth/login',
      logout: '/auth/logout',
      user: '/spa/user',
    },
    csrf: {
      cookie: 'XSRF-TOKEN',
      header: 'X-XSRF-TOKEN',
    },
    client: {
      retry: false,
    },
    redirect: {
      keepRequestedRoute: false,
      onLogin: false,
      onLogout: false,
      onAuthOnly: false,
      onGuestOnly: false,
    },
    globalMiddleware: {
      enabled: false,
      allow404WithoutAuth: true,
    },
    logLevel: 3,
  },
});
```

**Nuxt environment:**

-   Version: `3.13.0`
-   SSR Enabled: **no**
-   Environment: **local**

**Laravel environment:**

-   Version: `11.24.1`
-   Sanctum installed via Breeze: **yes**
-   [Checklist](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/authentication/spa-cookie#laravel-configuration) completed: **yes / no**
-   What is your session domain in `config/session.php`: `env('SESSION_DOMAIN')` (localhost in .env)
-   What is your stateful domains in `config/sanctum.php`: `explode(
        ',',
        env('SANCTUM_STATEFUL_DOMAINS', sprintf(
            '%s%s%s',
            'localhost,localhost:3000,127.0.0.1,127.0.0.1:8000,::1',
            Sanctum::currentApplicationUrlWithPort(),
            env('FRONTEND_URL') ? ',' . parse_url(env('FRONTEND_URL'), PHP_URL_HOST) : ''
        ))` (FRONTEND_URL is http://localhost:3000)
-   Content of `config/cors.php`:

```php
<?php

return [
    'paths' => ['*'],

    'allowed_methods' => ['*'],

    'allowed_origins' => [
        env('FRONTEND_URL', 'http://localhost:3000'),
        'chrome-extension://*',
        'safari-web-extension://*',
    ],

    'allowed_origins_patterns' => [],

    'allowed_headers' => ['*'],

    'exposed_headers' => [],

    'max_age' => 0,

    'supports_credentials' => true,
];
```

**Additional context**

All redirect options are set to false because i need to redirect users to a specific area of the app depending of who they are, but i think that this not affect anything because the problem is when loading user identity from api and it works until v0.4.16.

**Comment by manchenkoff** [comment]
Hey @ibrunotome, please try upgrading `ofetch` package to `1.4.0` or do Nuxt upgrade via `npx nuxi upgrade --force`

**Comment by ibrunotome** [comment]
It worked. Thanks!
