### ISSUE TITLE
[Docs] Add section about error handling

### ISSUE THREAD

**Issue by manchenkoff** [manchenkoff/nuxt-auth-sanctum#20]
Right now it is not clear to users how to properly handle API errors like `422` or `400` with additional details (e.g. errors dictionary). There is an example of handling in #5, but it should be documented in a package's readme file.

**Comment by manchenkoff** [comment]
Docs were added in a [GitBook](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/)

**Comment by martin-ro** [comment]
Just in time, Thanks!
