### ISSUE TITLE
[Bug] Logout on refresh page

### ISSUE THREAD

**Issue by GabrielFrohlich** [manchenkoff/nuxt-auth-sanctum#209]
**Description**
I've crated an aplication with this module, everything works fine but, when the page is reloaded, it seems the user logout from the backend

its like the cookie doesnt persist after a reload.

**To Reproduce**

1. Create a Nuxt APP with this module
2. Create a Laravel APP
3. Connect the frontend into the backend
4. Make the login
5. Refresh the page

**Expected behavior**

When the page is reloaded, the login needs to persist

**Actual behavior**

The user logout

**Module information**

-   Version: `^0.4.4`
-   Content of your `nuxt.config.ts`:

```typescript
// REPLACE WITH YOUR FILE CONTENT!
export default defineNuxtConfig({
    modules: ['nuxt-auth-sanctum'],

    sanctum: sanctum: {
    baseUrl: process.env.BACKEND_API, // Laravel API
    origin: import.meta.env.NODE_ENV === 'production' ? process.env.SANCTUM_ORIGIN_URL : 'http://localhost:3000',
    endpoints: {
      login: "/api/auth/login",
      logout: "/api/auth/logout",
    },
    redirect: {
      onLogin: '/',
      onLogout: '/login',
      onAuthOnly: '/login',
      onGuestOnly: '/'
    },
    globalMiddleware: {
      enabled: true
    }
  },
});
```

**Nuxt environment:**

-   Version: `3.13.1`
-   SSR Enabled: **yes**
-   Environment: **production**

**Laravel environment:**

-   Version: `11.9`
-   Sanctum installed via Breeze: **no**
-   [Checklist](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/authentication/spa-cookie#laravel-configuration) completed: **yes / no**
-   What is your session domain in `config/session.php`: `'domain' => env('SESSION_DOMAIN') // Replaced by .ninhodasgaitas.com.br in production`
-   What is your stateful domains in `config/sanctum.php`: `explode(',', env('SANCTUM_STATEFUL_DOMAINS', sprintf(
        '%s%s',
        'localhost,localhost:3000,127.0.0.1,127.0.0.1:8000,::1',
        Sanctum::currentApplicationUrlWithPort()
    ))) // replaced by app.ninhodasgaitas.com.br,app.ninhodasgaitas.com.br:443 in production`
-   Content of `config/cors.php`:

```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Cross-Origin Resource Sharing (CORS) Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may configure your settings for cross-origin resource sharing
    | or "CORS". This determines what cross-origin operations may execute
    | in web browsers. You are free to adjust these settings as needed.
    |
    | To learn more: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
    |
    */

    'paths' => ['api/*', 'sanctum/csrf-cookie'],

    'allowed_methods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],

    'allowed_origins' => ['*'],

    'allowed_origins_patterns' => [],

    'allowed_headers' => ['*'],

    'exposed_headers' => [],

    'max_age' => 0,

    'supports_credentials' => true,

]
```

**Comment by aliwesome** [comment]
I'm facing this issue on 0.4.18 version

**Comment by manchenkoff** [comment]
Hey @GabrielFrohlich, @aliwesome!

Have you tried upgrading the module to the latest version? 

_I will be able to take a closer look next week due to vacation._

**Comment by aliwesome** [comment]
Hey @manchenkoff Bon Voyage!

I might be missing something here, but I’ve been following these instructions to use local storage to persist the login state:
https://manchenkoff.gitbook.io/nuxt-auth-sanctum/usage/token-storage

I’m using the latest version, and I need to make sure the login state stays persistent so the user remains logged in even if they refresh the page. Any advice would be appreciated!

Thanks in advance!

**Comment by aliwesome** [comment]
@manchenkoff
Thank you so much for your advice! I’ve got it working in CSR mode now. Just wondering, is there any way we can enable this in SSR as well?

Thanks again!

**Comment by manchenkoff** [comment]
> Just wondering, is there any way we can enable this in SSR as well?

Yep, but it's incompatible with local storage since server doesn't have it, you can use default cookie storage, then it should work fine

**Comment by SkyNetRu** [comment]
I had the same problem because I had this in the config:

```
client: {
      initialRequest: false,
    }
```
So, when the page loads, the user is empty, which is why you get "not authenticated." But if you set 
```initialRequest: true```
then the app will send a request to get the user on load, and you will be authenticated.

**Comment by manchenkoff** [comment]
Hey @GabrielFrohlich, if you still have this issue, please provide more details by extracting logs as I described [here](https://github.com/manchenkoff/nuxt-auth-sanctum/issues/209#issuecomment-2421943663) assuming that you are using the latest version of the module.

**Comment by GabrielFrohlich** [comment]
Hello @manchenkoff ,
I have updated the Package to the last version, but it just worked when i made the same that @SkyNetRu 

Thanks by your attention

**Comment by manchenkoff** [comment]
> I have updated the Package to the last version, but it just worked when i made the same that @SkyNetRu

Glad to hear that! May I ask why you decided to disable `initialRequest` in the first place? It might help me to write docs better

**Comment by SkyNetRu** [comment]
`initialRequest: false` comes from some docs or some article maybe in Medium , I think when  I searched I copied that code

**Comment by GabrielFrohlich** [comment]
@manchenkoff In my case, it wasn't in nuxt.config.ts, I just added it with the true value

**Comment by manchenkoff** [comment]
> @manchenkoff In my case, it wasn't in nuxt.config.ts, I just added it with the true value

It's weird, this value is true by default from the module config 🤔
