### ISSUE TITLE
Package version inconsistency after release

### ISSUE THREAD

**Issue by TartanLeGrand** [manchenkoff/nuxt-auth-sanctum#22]
You have release the 0.0.15 but in the package.json you have 0.0.14.

https://github.com/manchenkoff/nuxt-auth-sanctum/blob/65e865ecc905f3a1a86bda65fdadb47c16f5cbfc/package.json#L3

**Comment by manchenkoff** [comment]
Thanks @TartanLeGrand, probably automation with changelog didn't work for some reason 😄

**Comment by TartanLeGrand** [comment]
Have you try https://github.com/googleapis/release-please ?

**Comment by manchenkoff** [comment]
Nope, this is a basic template from Nuxt modules, they already configured the same thing with PR creation, not sure what went wrong

**Comment by manchenkoff** [comment]
Fixed in #26
