### ISSUE TITLE
More Example

### ISSUE THREAD

**Issue by TartanLeGrand** [manchenkoff/nuxt-auth-sanctum#23]
Hello,

I'd like to ask you for a complete example for Laravel/Nuxt because I'm not sure that we all use Laravel with Breeze and Sanctum packages.

**Comment by manchenkoff** [comment]
Hey @TartanLeGrand, this package was created specifically for Sanctum authentication, it was not in my plan to support any other packages or authentication methods like token-based, there are already some Nuxt libraries that provide sufficient functionality. What kind of example do you suggest to put in this repo?

Btw, there is another repo with my initial experiment with complete Laravel and Nuxt setup (even before I created this package) - [Laravel & Nuxt](https://github.com/manchenkoff/nuxt-laravel).

**Comment by gitekDev** [comment]
@manchenkoff for me its interesting how to implement .net api auth  (.net 8 new api identity auth) with Nuxt.

**Comment by manchenkoff** [comment]
Hey @gitekDev! As far as I know, there are no other packages with cookie-based authentication support for Nuxt 3 yet, but for .NET specifically, you can use a similar approach as I used in the article shared above for PHP.

On the backend side everything should be possible by using the default authentication layer - [ASP.NET Core Docs](https://learn.microsoft.com/en-us/aspnet/core/security/authentication/cookie?view=aspnetcore-8.0), and here is also an [example of the project](https://github.com/dotnet/aspnetcore/tree/main/src/Security/samples/Cookies) with a configured cookie-based session.

On the Nuxt side, you just need to adjust endpoints and cookie/header names according to your API (right now I am not sure which keys are used by .NET).

P.S. Actually, it might be a good candidate for a framework-agnostic open-source project and if you wish, we can collaborate on implementation 😎 I believe it might be handy for any other languages as well like Python, Go, etc

**Comment by manchenkoff** [comment]
I'm closing this one due to inactivity, in case of any ideas about new projects - feel free to reach out to me on any social media! 👌
