### ISSUE TITLE
useSanctumClient() does not show typescript warnings

### ISSUE THREAD

**Issue by alexandrmucha** [manchenkoff/nuxt-auth-sanctum#232]
Hi, I would like to use `client` from `const client = useSanctumClient()` instead of `$fetch`. The problem is that I am not getting the typescript warnings like I am used to with `$fetch`. Is this a bug, or can I turn it on somehow? I use visual studio code.

```
const client = useSanctumClient();

const { data } = await useAsyncData('itemData', () =>
  client(`/item/${id}/data`)
);
```

**Comment by manchenkoff** [comment]
Hey @alexandrmucha, what kind of warnings do you expect from this code? 

I don't think it is a bug since `useSanctumClient` returns an instance of `$fetch.create()`. You can see more details here - [Docs](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/usage/composables/usesanctumclient).

**Comment by manchenkoff** [comment]
@alexandrmucha the composable function `useSanctumClient` returns an instance of `$Fetch`, which is constructed as `fetch.create()` inside of the plugin. However, I see that `$fetch` function is also defined as `$Fetch` type here - [unjs/ofetch](https://github.com/unjs/ofetch/blob/bdfb50735d9ed3a46a9cf13395da7498c053f599/src/fetch.ts#L263) but later Nuxt adds customisation on top of it to make this composable exported automatically and to be used in `useFetch`, `useAsyncData`, etc.

So, the reason of the difference in your case is ``client(`/product/${productId}`)`` returns `any` as response, while ``$fetch(`/product/${productId}`)`` returns `unknown`. If you want to enable the same warnings, you can use either `object` or `unknown` as a type of repsonse

```typescript
<template>
  <div>
    <p>Product name: {{ data.name }}</p>
    <p>Product ID: {{ data.id }}</p>
  </div>
</template>

<script lang="ts" setup>
const client = useSanctumClient();
const route = useRoute();

const productId = Array.isArray(route.params.id) ? route.params.id[0] : route.params.id;

const { data } = await useAsyncData('product', () =>
  client<unknown>(`/product/${productId}`)
);
</script>
```
