### ISSUE TITLE
Cant get sanctum.token.cookie for auth

### ISSUE THREAD

**Issue by kca66y** [manchenkoff/nuxt-auth-sanctum#236]
I use nuxt - csr mode with pm2.
dev server, ip address as a host.
laravel server also located on this server. 
i made a [nginx config](https://gist.github.com/kca66y/d53e0b8523b699b6e748dcdf7d607bfe)

your module i use with token mode. When i locally test this everything alright, but on server i get 401 on user/me

-   Version: ^0.5.0,
-   Content of your `nuxt.config.ts`:

```typescript
export default defineNuxtConfig({

  // ssr: false,

  // runtimeConfig: {
  //   public: {
  //     baseURL: 'http://ip/api/v1',
  //   },
  // },

  devtools: { enabled: false },
  css: ['~/assets/css/main.css'],

  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },

  modules: [
    'nuxt-svgo',
    'nuxt-auth-sanctum',
    'radix-vue/nuxt',
    '@pinia/nuxt',
    '@vueuse/nuxt',
  ],

  sanctum: {
    // globalMiddleware: {
    //   enabled: true,
    // },
    // logLevel: 5,
    mode: 'token',
    baseUrl: 'http://ip/api/v1', // Laravel API
    endpoints: {
      // csrf: 'http://localhost:8000/sanctum/csrf-cookie',
      user: '/users/me',
      login: '/auth/login',
      logout: '/auth/logout',
    },
  },

  svgo: {
    global: false,
    // autoImportPath: '~/assets/icons/',
    defaultImport: 'component',
    // componentPrefix: 'icon',
  },
});
```

**Nuxt environment:**

-   Version: `3.14.0`
-   SSR Enabled: **yes**
-   Environment: **production**

**Laravel environment:**

-   Version: `11.9`
-   Sanctum installed via Breeze: **no**
-   [Checklist](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/authentication/spa-cookie#laravel-configuration) completed: **yes**
-   What is your session domain in `config/session.php`: `.ip`
-   What is your stateful domains in `config/sanctum.php`: `[]`
-   Content of `config/cors.php`:

```php
<?php

return [
       'paths' => ['api/*', 'sanctum/csrf-cookie'],

    'allowed_methods' => ['*'],

    'allowed_origins' => ['http://ip'],

    'allowed_origins_patterns' => [],

    'allowed_headers' => ['*'],

    'exposed_headers' => [],

    'max_age' => 0,

    'supports_credentials' => true,
];
```

**Logs**
![telegram-cloud-document-2-5321323286989135392](https://github.com/user-attachments/assets/3658fcc9-5756-4489-9f5b-74e5c01d0be1)

**Comment by manchenkoff** [comment]
Hey @kca66y, I see that you do not have a token in the storage which is the reason of getting 401 response. Please, make sure that you have correct response from the API according to the docs [here](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/authentication/api-token). This `token` value will be stored as a cookie and later be used as a header for consequent requests.

**Comment by manchenkoff** [comment]
@kca66y can you check if you have cookie as well in your browser?

**Comment by kca66y** [comment]
<img width="1133" alt="Снимок экрана 2024-11-18 в 14 19 27" src="https://github.com/user-attachments/assets/0aa5d642-548d-4a72-aef2-673a272565c2">

**Comment by manchenkoff** [comment]
Thanks, for some reason you don't have your token stored in cookies. Could you please provide a code sample of your login functionality in Nuxt app and login action of Laravel controller. I will try to investigate potential issues later today.

**Comment by kca66y** [comment]
```js
const { login } = useSanctumAuth();

const state = reactive({
  identifier: '',
  password: '',
});

async function onSubmit(event) {
  try {
    await login(state);
  } catch (error) {
    recordErrors(error.data);
  }
}
```

```php
public function login(LoginUserRequest $request)
    {
        $user = $this->authService->login(LoginUserDTO::from($request->validated()));

        if (!$user) {
            return response()->json(['error' => __('auth.failed')], Response::HTTP_UNAUTHORIZED);
        }

        $token = $this->authService->createBearerToken($user);

        if (!$token) {
            return response()->json(['error' => __('auth.failed')], Response::HTTP_UNAUTHORIZED);
        }

        return response()->json(['token' => $token]);
    }
```

**Comment by kca66y** [comment]
Yeah, on local everything good

**Comment by kca66y** [comment]
@manchenkoff any ideas?

**Comment by manchenkoff** [comment]
> @manchenkoff any ideas?

I haven't looked into it yet, will keep you posted

**Comment by manchenkoff** [comment]
Please, try the latest version `0.5.2`. Feel free to re-open this issue if the problem persists.
