### ISSUE TITLE
[Bug] Still logged in after logout

### ISSUE THREAD

**Issue by OrPh4ns** [manchenkoff/nuxt-auth-sanctum#238]
const {logout, user} = useSanctumAuth();

const signout = async () => {
  await logout();
  current_branch_name.value = null;
  current_branch_number.value = null;
  current_branch_role.value = null;
}

this is the function to logout but user still logged in after redirect to login page and refresh again

**Comment by OrPh4ns** [comment]
Yes on logout user became null but on refreshing page all data getting back like XSRF-TOKEN and rest of data.

there is no error in console

**Comment by OrPh4ns** [comment]
from Telescope showing logout is success  

![grafik](https://github.com/user-attachments/assets/e32ff690-bb9e-4494-bdba-fff25f2373f4)


![grafik](https://github.com/user-attachments/assets/53581ae3-ab3b-4fdc-b9d8-54597872e454)

**Comment by manchenkoff** [comment]
I see @OrPh4ns, thanks for more info. Could you please check if the cookie with a token is also deleted after you logged out?

**Comment by OrPh4ns** [comment]
@manchenkoff 

![Bildschirmfoto 2024-11-21 um 12 34 24](https://github.com/user-attachments/assets/490af16c-942b-46b0-a6b2-b0e3eb848559)
![Bildschirmfoto 2024-11-21 um 12 35 38](https://github.com/user-attachments/assets/a4aec70f-03ab-4490-a90f-32f2d129c7ad)
![Bildschirmfoto 2024-11-21 um 12 37 50](https://github.com/user-attachments/assets/a6b82d3b-4efc-4207-b6cc-30ff733cd5d4)

**Comment by OrPh4ns** [comment]
Laravel
Version: 11.33
    Sanctum installed via Breeze: **no**
    [Checklist](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/authentication/spa-cookie#laravel-configuration) completed: yes
    What is your session domain in config/session.php: SESSION_DOMAIN=localhost
    What is your stateful domains in config/sanctum.php: localhost:3003

log level is 5 but project does not create any log file

**Comment by manchenkoff** [comment]
> log level is 5 but project does not create any log file

it depends on how you configured your environment, if you are running app by `npm run dev`, then you should have all logs in console output for SSR mode and also you can see all CSR logs in your browser

**Comment by manchenkoff** [comment]
> What is your session domain in config/session.php: SESSION_DOMAIN=localhost

sometimes it works not very well, try to comment this setting in `.env` and restart app/reload configs as well

**Comment by manchenkoff** [comment]
Closed due to inactivity, feel free to re-open once more details and repro are available
