### ISSUE TITLE
[Feature] Allow manually re-fetching user

### ISSUE THREAD

**Issue by nfunwigabga** [manchenkoff/nuxt-auth-sanctum#24]
It might be useful to expose the `refreshIdentity` method in the `useSanctumAuth` composable. This would permit refreshing the logged in user on-demand. Comes in handy when for instance a user profile is updated and we need to make the updated properties reflect in other parts of the application (such as refreshing an Avatar image in navigation menu).

**Comment by manchenkoff** [comment]
Hey @nfunwigabga, sounds good! I'll try to implement it once have enough time, but feel free to open a PR if you want to contribute 👌

**Comment by manchenkoff** [comment]
published as [v0.0.17](https://github.com/manchenkoff/nuxt-auth-sanctum/releases/tag/v0.0.17)
