### ISSUE TITLE
[nuxt-auth-sanctum:ssr]  ERROR  Unable to load user identity from API [GET] "http://localhost:8000/api/user": <no response> fetch failed

### ISSUE THREAD

**Issue by stefenzzz** [manchenkoff/nuxt-auth-sanctum#240]
when unauthenticated, each refresh logs this error, should it be logging the correct error unauthorized 401

**Comment by manchenkoff** [comment]
Hey @stefenzzz, the error `<no response> fetch failed` tells you that your API server is not reachable for your Nuxt app and it is not related to the module itself. It might be related to your environment (e.g. docker) or that server has a different address for SSR calls. If you want help, please re-create the issue with `Bug Report` template and provide all necessary details there.

**Comment by stefenzzz** [comment]
> Hey @stefenzzz, the error `<no response> fetch failed` tells you that your API server is not reachable for your Nuxt app and it is not related to the module itself. 

my bad I wasn't able to identify it myself, I was engage in different work loads didn't further investigate the problem and directly posted it here, anyways thanks for the response.
