### ISSUE TITLE
[Feature] Add passkey to authenticate

### ISSUE THREAD

**Issue by Achraf931** [manchenkoff/nuxt-auth-sanctum#270]
Is it possible to add the possibility of creating passkeys to connect, like what Github offers, here's an image :
<img width="1512" alt="Capture d’écran 2024-12-24 à 11 13 52" src="https://github.com/user-attachments/assets/ea01907a-35a5-4253-9293-1bef5ebcadc0" />
<img width="1512" alt="Capture d’écran 2024-12-24 à 11 16 17" src="https://github.com/user-attachments/assets/9eb572f6-dba7-4200-871d-f54e207d9ede" />

**Comment by manchenkoff** [comment]
Hey @Achraf931, this module provides only the functionality required by Laravel Sanctum. Passkeys are out of the scope and not supported by Laravel natively, so the answer is no 😞 You can check more details about Sanctum functionality [here](https://laravel.com/docs/11.x/sanctum).
