### ISSUE TITLE
[Bug] Cannot use plugin dependencies properly 

### ISSUE THREAD

**Issue by npldevfr** [manchenkoff/nuxt-auth-sanctum#271]
**Describe the bug**
Hello, I followed the [documentation](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/advanced/plugin-dependencies) using i18n to wait for initialization, but it resulted in issues with SSR requests.

The problem is that I got a 500 error when the plugin makes its initial request to my API. This happens because the Content-Type header is not set to application/json when overriding the code (see the reproduction steps).

**To Reproduce**

<img width="702" alt="Capture d’écran 2024-12-25 à 12 48 34" src="https://github.com/user-attachments/assets/77abbbd2-32b6-4664-8e7d-0ebc2124b154" />
Screenshot of logs using the following code

```typescript
// app.config.ts
export default defineAppConfig({
  sanctum: {
    interceptors: {
      onRequest: (app: NuxtApp, ctx: FetchContext, _: ConsolaInstance) => {
        console.log(ctx.options.headers)
        ctx.options.headers = {
          ...ctx.options.headers,
          'X-Locale': app.$i18n.localeProperties.value.code || 'en',
        }
      },
    },
  },
})

``` 

```typescript
//plugins/custom-auth.ts
export default defineNuxtPlugin({
  name: 'authentication',
  dependsOn: ['i18n:plugin', 'nuxt-auth-sanctum'],
  async setup() {
    const { init } = useSanctumAuth()
    await init()
  },
})
```

<img width="966" alt="Capture d’écran 2024-12-25 à 12 50 55" src="https://github.com/user-attachments/assets/657ddd14-eaef-46cd-be33-93e5347ea413" />

**Module information**

-   Version: `0.5.2`
-   Content of your `nuxt.config.ts`:

```typescript
export default defineNuxtConfig({
    modules: ['nuxt-auth-sanctum'],

    sanctum: {
    redirectIfAuthenticated: false,
    redirectIfUnauthenticated: false,
    appendPlugin: true,
    mode: 'cookie',
    endpoints: {
      user: '/api/v1/user',
    },
    client: {
      retry: false,
      initialRequest: false,
    },
    globalMiddleware: {
      enabled: false,
      allow404WithoutAuth: true,
    },
  },
});
```

**Nuxt environment:**

-   Version: `3.14`
-   SSR Enabled: **yes**
-   Environment: **local**

**Laravel environment:**
Working properly without custom instanced by plugin

**Logs**

```log
[nuxt-auth-sanctum:ssr]  WARN  [response] set-cookie header is missing


[nuxt-auth-sanctum:ssr]  WARN  [response] content-type header is missing or invalid


[nuxt-auth-sanctum:ssr]  WARN  [response] access-control-allow-credentials header is missing or invalid


[nuxt-auth-sanctum:ssr]  WARN  [response] access-control-allow-origin header is missing or invalid
```

**Additional context**

If this is unclear, i will be able to provide more details!

**Comment by manchenkoff** [comment]
Hey @npldevfr, can you try this headers enrichment approach instead?

```typescript
ctx
  .options
  .headers
  .set('X-Locale', app.$i18n.localeProperties.value.code || 'en')
```

**Comment by npldevfr** [comment]
It works better now! However, I'm still stuck on this screen, is that normal?

<img width="697" alt="Capture d’écran 2024-12-25 à 15 02 46" src="https://github.com/user-attachments/assets/67195db7-1825-4cff-ac92-3c6351fd9c25" />

**Comment by manchenkoff** [comment]
This error is generally fine if you didn't sign in as a user, but I cannot tell for sure since it depends on how you code this. If you see this error after successfully logging in, it might be an incorrect configuration. 

However, since this issue is unrelated to plugin dependencies, I recommend opening another issue with the **Bug report** template and providing more details there.

**Comment by npldevfr** [comment]
OK! But it seems like the request will be made even if I don't have a session cookie stored. Is this a real use case or an unhandled case?

**Comment by manchenkoff** [comment]
> OK! But it seems like the request will be made even if I don't have a session cookie stored. Is this a real use case or an unhandled case? (about the /user request)

Correct, it will be made to pass empty user to middleware for page restriction. You just need to handle expected errors as not critical for your app (if applicable). Here is an [example](https://github.com/manchenkoff/nuxt-auth-sanctum/blob/main/src/runtime/plugin.ts#L62) of how I treat 401 in the default implementation. You can do something similar since you disabled the default initialization approach.

**Comment by npldevfr** [comment]
Works fine thanks !
