### ISSUE TITLE
[question] baseUrl keep caching

### ISSUE THREAD

**Issue by ezekel** [manchenkoff/nuxt-auth-sanctum#274]
Hi @manchenkoff 

I have problem I tried to changed the baseUrl or even I comment out . When I tried to submit the login, I see in my console it keeps calling the `http://larabells.local` . I tried to delete my docker images and rebuild. but no luck.

![image](https://github.com/user-attachments/assets/6179f5c0-52f3-48f5-ac2d-7594574242f4)

![image](https://github.com/user-attachments/assets/c5efa10f-8bea-435b-9635-c99811961c55)

Thank you in advance.

**Comment by manchenkoff** [comment]
Hey @ezekel, the module doesn't cache anything on its side, but your `.env` file may override this config, please make sure that you don't have `NUXT_PUBLIC_SANCTUM_BASE_URL=http://larabells.local` there. 

Commenting out this line in your `nuxt.config.ts` should use the default value which is `http://localhost:80`. However, you can also try `npx nuxi cleanup` to clean the project from the previous artefacts.

I have just tried changing the value, commenting it out, and overriding it via `.env` but couldn't reproduce your behaviour.

**Comment by ezekel** [comment]
Thank you for the reply. I will just close this maybe on my configuration or my docker.

**Comment by ezekel** [comment]
Thank you for the reply you're right I have .env in my nuxt folder I forgot I have this `NUXT_PUBLIC_SANCTUM_BASE_URL`.

Thank you again
