### ISSUE TITLE
Helper Function `$fetchSanctum`

### ISSUE THREAD

**Issue by SDIjeremy** [manchenkoff/nuxt-auth-sanctum#35]
How can we use `useSanctumClient` as a utility / helper in the same way we use `$fetch` in Nuxt now?

**Comment by manchenkoff** [comment]
Hey @SDIjeremy, have you checked this page in docs? [Usage of useSanctumClient](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/usage/composables/usesanctumclient)

**Comment by SDIjeremy** [comment]
Yes, my question is is there a way to use `useSanctumClient` as a global helper without defining it in every place? Similar to how you use `$fetch` with Nuxt.

**Comment by manchenkoff** [comment]
@SDIjeremy

Oh, now I see what you mean 😄 

Yes, it is definitely possible by creating additional util file, [here ](https://nuxt.com/docs/guide/directory-structure/utils) you can find more details. You can create `sanctum.ts` file in the `utils` directory with the following content (or similar)

```typescript
export default const $fetchSanctum = useSanctumClient();
```

It should be auto-imported by your Nuxt application and available in other files as `$fetchSanctum`, so to make a request you just need to call it like in your example

```typescript
await $fetchSanctum('/api/endpoint');
```

**Comment by SDIjeremy** [comment]
Let me try that, I thought I did that already and was getting an error, but let me give it a try again.

**Comment by SDIjeremy** [comment]
I'm getting this error, which is what I was getting before:
`Uncaught (in promise) Error: $fetchSanctum is not a function`
```js
const { data, error }: { data: Ref<Account.AccountResponse>, error: Ref } = await useAsyncData(`accounts`, async () => {
    return await $fetchSanctum(`/api/accounts`);
});
```

**Comment by manchenkoff** [comment]
Not sure why you got this error, but it looks like it won't work anyway, since I tried my recommendation with the util file and got this

```
A composable that requires access to the Nuxt instance was called outside of a plugin, Nuxt hook, Nuxt middleware, or Vue setup function
```

I believe that `utils` import works outside of those scopes and cannot access the defined Nuxt plugin. Since `$fetch` utility just provides an interface to `ofetch` library, we cannot do it in the same way with Sanctum plugin.

**Comment by SDIjeremy** [comment]
is there any way we can replace `$fetch` entirely or maybe instead just force `$fetch/ofetch` to use the CSRF cookie headers from the authentication?

**Comment by manchenkoff** [comment]
No, this is actual reason why this package was created, there is no easy way to change the global behavior of Nuxt / ofetch tools. Moreover, it is a bad-practice to use `$fetch` helper everywhere anyway since it is not always compatible with SSR.
