### ISSUE TITLE
XSRF-TOKEN unauthorised please help

### ISSUE THREAD

**Issue by marcusaaronb** [manchenkoff/nuxt-auth-sanctum#36]
XSRF-TOKEN unauthorised please help

**Comment by marcusaaronb** [comment]
![Uploading Screenshot 2024-02-26 at 1.49.46 PM.png…]()

**Comment by marcusaaronb** [comment]
Login api is ok but if access inside middleware return 401 unauthorized

**Comment by manchenkoff** [comment]
Hey @marcusaaronb, the attached screenshot is not valid, but I assume that your issue is similar to #34, please provide more details there
