### ISSUE TITLE
`v0.1.x` with Nuxt `3.10`

### ISSUE THREAD

**Issue by SDIjeremy** [manchenkoff/nuxt-auth-sanctum#38]
I'm getting a ton of errors and my site isn't working when upgrading from `v0.0.14` to `v0.1.1`
I noticed in the releases that it mentions Nuxt `3.9` and `3.10`, should I downgrade my Nuxt?

**Comment by jjjrmy** [comment]
It seems that the Env `NUXT_PUBLIC_SANCTUM_BASE_URL` no longer is being used and instead you have to set it in the runtime config, that's what fixed it for me.
https://github.com/manchenkoff/nuxt-auth-sanctum/blob/497386bfe5d9745331955197600df8933532e94f/test/fixtures/basic/nuxt.config.ts#L6-L11

**Comment by manchenkoff** [comment]
`NUXT_PUBLIC_SANCTUM_BASE_URL` is used to overwrite the value in the runtime config, but it should be described in either module config or runtime config at least once

**Comment by SDIjeremy** [comment]
> `NUXT_PUBLIC_SANCTUM_BASE_URL` is used to overwrite the value in the runtime config, but it should be described in either module config or runtime config at least once

I don't think that was the case before, as originally I had it only set in my ENV, but after updating to the latest version I was getting errors because it was trying to query `/api/user` without a baseUrl.
