### ISSUE TITLE
Losing Authenticated State on Page Refresh

### ISSUE THREAD

**Issue by tcampbPPU** [manchenkoff/nuxt-auth-sanctum#4]
I have a similar setup to the nuxt pages you have in your playground, however after I login and lets say im on the profile page and I refresh the page i lose my authenticated state and I am redirected back to the login screen.

**Comment by manchenkoff** [comment]
Hey @tcampbPPU, if your state resets, I assume that your server-side and client-side requests use different CSRF tokens in headers. 
Could you provide more details like configurations and requests/responses (with headers/cookies) for the client and server to investigate the issue? 
Also, make sure that you configured `origin` in your `nuxt.config.ts` to let API understand that the server and client are the same

**Comment by tcampbPPU** [comment]
This is what my `nuxt.config.ts` looks like:
```ts
sanctum: {
    baseUrl: 'http://localhost:8000', // via running php artisan serve
    origin: 'http://localhost:3000', // Nuxt app
    userStateKey: 'sanctum.user.identity',
    client: {
        retry: false,
    },
    redirect: {
        keepRequestedRoute: true,
        onAuthOnly: '/login',
        onGuestOnly: '/profile',
        onLogin: '/dashboard',
        onLogout: '/logout',
    },
},
```
I think using `http://localhost:8000` is problematic for some reason

**Comment by manchenkoff** [comment]
It shouldn't be problematic since I use the same hosts locally for several projects. Is it right that your Nuxt app uses SSR and was registered in Laravel config as a stateful domain?

Btw, providing some examples of requests and responses with cookies and headers is still valid, it will be much easier to understand on what side you have the problem.

**Comment by hrnicek** [comment]
I have same problem.

**Comment by manchenkoff** [comment]
Hey @hrnicek, can you share the configuration of Laravel auth and examples of client and server responses from the nuxt side?

**Comment by manchenkoff** [comment]
@tcampbPPU, @hrnicek is this issue still valid or did you fix the configuration? I couldn't reproduce this problem on fresh projects

**Comment by YeftaAW** [comment]
Yeah, same here, with laravel 10

**Comment by manchenkoff** [comment]
@YeftaAW can you provide your configs (Nuxt / Laravel) and HTTP responses from Laravel to both your CSR and SSR requests from Nuxt?

**Comment by YeftaAW** [comment]
Nuxt:
```
sanctum: {
    baseUrl: 'http://localhost:8000', // Laravel API
    origin: 'http://localhost:3000', // Nuxt app,
}
```

And everything on laravel is just default one copied from `.env.example` with (only updated DB config).

But I have this error when running on `nuxt dev`:
```
Unable to load user identity FetchError: [GET] "http://localhost:8000/api/user": <no response> fetch failed
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $fetch2 (file:///project_dir/front/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:261:15)
    ... 5 lines matching cause stack trace ...
    at async createNuxtAppServer (/project_dir/front/node_modules/nuxt/dist/app/entry.js:24:7)
    at async default (file:///project_dir/front/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:33:18)
    at async Object.renderToString (file:///project_dir/front/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19) {
  [cause]: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11372:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async $fetchRaw2 (file:///project_dir/front/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:219:26)
      at async $fetch2 (file:///project_dir/front/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:261:15)
      at async /project_dir/front/node_modules/nuxt-auth-sanctum/dist/runtime/plugin.mjs:23:120
      at async setup (/project_dir/front/virtual:nuxt:/project_dir/front/.nuxt/plugins/server.mjs:38:116)
      at async Object.callAsync (file:///project_dir/front/node_modules/unctx/dist/index.mjs:72:16)
      at async applyPlugin (/project_dir/front/node_modules/nuxt/dist/app/nuxt.js:115:25)
      at async Module.applyPlugins (/project_dir/front/node_modules/nuxt/dist/app/nuxt.js:135:7)
      at async createNuxtAppServer (/project_dir/front/node_modules/nuxt/dist/app/entry.js:24:7) {
    cause: Error: connect ECONNREFUSED ::1:8000
        at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
        at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 8000
    }
}
```

**Comment by manchenkoff** [comment]
@YeftaAW this error is irrelevant to the package itself since there is no server on this address, make sure that you are using 8000 and not 80 port in your Laravel app

**Comment by manchenkoff** [comment]
Published new version v0.0.10 with some fix which might help with the state losing (theoretically), [here](https://github.com/manchenkoff/nuxt-auth-sanctum/commit/351996347c5fb710c56190bbb4a244cf715f3ffa) are the changes. Please, try to upgrade.

For now, I'm closing this issue, feel free to re-open it if you have any problems.

**Comment by martinjdlabs** [comment]
Im having the same problem. I cant get the connection between my local laravel and my nuxt project to work. I do get it to work when using like postman or insomnia.

// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  extends: ["@nuxt/ui-pro"],
  modules: [
    "@nuxt/ui",
    "@pinia/nuxt",
    "nuxt-icon",
    "@nuxt/image",
    "@pinia-plugin-persistedstate/nuxt",
    "@nuxt/content",
    "nuxt-auth-sanctum",
  ],

  build: {
    transpile: ["pinia-plugin-persistedstate"],
  },

  sanctum: {
    baseUrl: "http://localhost:8000/", // Laravel
    origin: "http://localhost:3000/", // Nuxt app
  },
});


APP_URL=http://localhost:8000/
APP_DOMAIN=localhost
FRONTEND_URL=http://localhost:3000


BROADCAST_DRIVER=log
CACHE_DRIVER=file
FILESYSTEM_DISK=local
QUEUE_CONNECTION=database
SESSION_DRIVER=cookie
SESSION_LIFETIME=120
SESSION_DOMAIN=localhost
SANCTUM_STATEFUL_DOMAINS=localhost:3000

I both get CORS error when doing the login func. And get the following when using isiAuthenticated func

Unable to load user identity FetchError: [GET] "http://localhost:8000/api/user": <no response> fetch failed
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $fetch2 (file:///Users/jdlabs02/Documents/Reuseit%20products%20Admin/reuseitAdminNuxt/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:261:15)
    ... 5 lines matching cause stack trace ...
    at async createNuxtAppServer (/Users/jdlabs02/Documents/Reuseit products Admin/reuseitAdminNuxt/node_modules/nuxt/dist/app/entry.js:24:7)
    at async default (file:///Users/jdlabs02/Documents/Reuseit%20products%20Admin/reuseitAdminNuxt/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:33:18)
    at async Object.renderToString (file:///Users/jdlabs02/Documents/Reuseit%20products%20Admin/reuseitAdminNuxt/node_modules/vue-bundle-renderer/dist/runtime.mjs:173:19) {
  [cause]: TypeError: fetch failed
      at Object.fetch (node:internal/deps/undici/undici:11372:11)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async $fetchRaw2 (file:///Users/jdlabs02/Documents/Reuseit%20products%20Admin/reuseitAdminNuxt/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:219:26)
      at async $fetch2 (file:///Users/jdlabs02/Documents/Reuseit%20products%20Admin/reuseitAdminNuxt/node_modules/ofetch/dist/shared/ofetch.00501375.mjs:261:15)
      at async /Users/jdlabs02/Documents/Reuseit products Admin/reuseitAdminNuxt/node_modules/nuxt-auth-sanctum/dist/runtime/plugin.mjs:23:120
      at async setup (/Users/jdlabs02/Documents/Reuseit products Admin/reuseitAdminNuxt/virtual:nuxt:/Users/jdlabs02/Documents/Reuseit products Admin/reuseitAdminNuxt/.nuxt/plugins/server.mjs:48:116)
      at async Object.callAsync (file:///Users/jdlabs02/Documents/Reuseit%20products%20Admin/reuseitAdminNuxt/node_modules/unctx/dist/index.mjs:72:16)
      at async applyPlugin (/Users/jdlabs02/Documents/Reuseit products Admin/reuseitAdminNuxt/node_modules/nuxt/dist/app/nuxt.js:115:25)
      at async Module.applyPlugins (/Users/jdlabs02/Documents/Reuseit products Admin/reuseitAdminNuxt/node_modules/nuxt/dist/app/nuxt.js:135:7)
      at async createNuxtAppServer (/Users/jdlabs02/Documents/Reuseit products Admin/reuseitAdminNuxt/node_modules/nuxt/dist/app/entry.js:24:7) {
    cause: Error: connect ECONNREFUSED ::1:8000
        at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
        at __node_internal_exceptionWithHostPort (node:internal/errors:671:12)
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 8000
    }
  }
}

**Comment by manchenkoff** [comment]
Hey @martinjdlabs, here are few things which might help:
- remove `SESSION_DOMAIN=localhost` since it's not necessary for localhost domain (afaik it won't work anyway)
- try to replace `localhost` in your nuxt configs with `127.0.0.1`
- make sure that you can call your app at `127.0.0.1:8000` via curl or ping (from the command terminal)

Your error means that there is no server at this address, so the problem is in the configurations
```json
{
    errno: -61,
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '::1',
    port: 8000
}
```

**Comment by manchenkoff** [comment]
@martinjdlabs if the replacement with `127.0.0.1` helped, then you should also configure Laravel accordingly in order to recognize `STATEFUL_DOMAIN`. If the frontend sends header with `127.0.0.1:3000`, you should use exactly the same value in your `.env` config

**Comment by martinjdlabs** [comment]
Still can't login, I really can't understand why it works via insomnia and not the nuxt project. I really appreciate your help! 
![Uploading Skärmavbild 2023-11-21 kl. 12.06.00.png…]()

**Comment by manchenkoff** [comment]
@martinjdlabs try to also adjust `APP_URL` in your `.env` file, it should be `127.0.0.1:8000` and `FRONTEND_URL` should be the same as `STATEFUL_DOMAIN`.

and could you also share the details of the error you receive in the browser?

**Comment by manchenkoff** [comment]
[Here](https://github.com/manchenkoff/nuxt-laravel) is also an example repo which I used in [my article](https://medium.com/@manchenkoff/laravel-10-and-nuxt-3-setup-ssr-with-authentication-from-scratch-497ab1a3fc56) before the creating this module, try to check this out in order to compare with your configs or maybe go through the article as step-by-step approach to make sure that you didn't miss any configuration.

**Comment by martinjdlabs** [comment]
Respone headers
`HTTP/1.1 204 No Content
Host: 127.0.0.1:8000
Date: Tue, 21 Nov 2023 11:47:59 GMT
Connection: close
X-Powered-By: PHP/8.2.6
Cache-Control: no-cache, private
Date: Tue, 21 Nov 2023 11:47:59 GMT
Access-Control-Allow-Origin: http://127.0.0.1:3000
Set-Cookie: XSRF-TOKEN=eyJpdiI6InVJbkhXK0l0R3ZzVnY5UWJlWW9UNFE9PSIsInZhbHVlIjoia0hBcFFEQUU0MERhQVVPaWZyT1Nic2VNU2NYMm5BL0xMbnp6OGlnVjZMSytRaDhSTitvMUFyaXovRGtDSTZ2RHlrbTg0WC9veDVlNkdpZnZaNzVFUDk4Q3MxKzBleDNvVWpxckZtL0dIbWxPVmExZjduU1VLUGtCdk5xNXJwODEiLCJtYWMiOiIxNDVkNmE2YjQ0M2U0NWQzMGE1MDIxYWFhNTczYTcyZmYyOTE4NGZhYzEzOWE3NTM3NGU3OWIwM2Y3MDAyMDhjIiwidGFnIjoiIn0%3D; expires=Tue, 21 Nov 2023 13:47:59 GMT; Max-Age=7200; path=/; samesite=lax
Set-Cookie: reuseit_core_session=eyJpdiI6IlEwUUFrTmJuQzVUSkord3ZZNGpxTFE9PSIsInZhbHVlIjoienYvWDhnM1JGeU1RbnVCdTdjZUpvd0crUURzUC9QY25vMjE4Zk1OdG9zL09DMjlGS1NEL3cxTXhEZmlXQkJMUHhYeUFSa0JDV2Nac1VRR3BaU1I5bS9SUW91dW5mWlBLQk44THZiRVFNUGdJeE5xZVNiNmJVNEpJM01pRTBEc2YiLCJtYWMiOiJkOGNmODA3ZTZhY2RkYmE4MjE5MzJhN2VlMjg4N2FmMDVjYzlmMDkxNTRlZDI4NWE5YjlhYWM4ZmZjZjEwMjgyIiwidGFnIjoiIn0%3D; expires=Tue, 21 Nov 2023 13:47:59 GMT; Max-Age=7200; path=/; httponly; samesite=lax
Set-Cookie: 3YbvUXEKhbfts4hD0kXysHkHDajcw6pDsaOJMzOH=eyJpdiI6InM5NVpodzdhalZxZlpxUC9Fa2FNM3c9PSIsInZhbHVlIjoicTdqajh3UFVRLytYVTFsZjhTcGdzSVZLK0g0SUtEelU0T29oblZrK1BtR1NqZ0RMeEMzeUwwQ3hlZWFSS3g2d1VNSkc3VGJKSEU4K3pNYi83bTRzYTRMYXN6V1BBZWJsRFI0SnVoQ29sNXV4dndHV3E4dFRWdm5uaFNkVnRwZU5GelpZRFgyZ1Jrb0RpdmhQMytjYUlmU0lldHl4UXAySlV6M01mY3BQUFpyLzFiR2ZmK3ZqRTRib1F5WjZRT1loekRZUStSamRsMEFDc242NjBCdmVqVGIrcnNmYy94UFpMV3BQdUZ2Wi9jbWtFekdwcUgzYmJMTEJxUFdFSDZjZ1NKWnBXY2lTMjNtbktOR1BBMGowcncyOUFFSmViZVpqZXJRWjgxMmN4T3l0Z2lNWXpqaS9ERHlkb29OVENQVFczTVVodXBIWmdoMjVSa3RQNGd5S093SytGZC81UE9CVlgydEUxclFyUlk3bVMxU0JqK29pR3N4VER1NGJlc3c3VDAxM2VFZGtIRXJFcXpjQzl1WG56QT09IiwibWFjIjoiM2U3NWUwOGExZDEzOTIxYzI0ZjEwNmU1ZGFlMWFjOTI1Mjc0NTY4MDZlNjJlYzVjNjU3MGIxZjQ0NDg5ODQ1MyIsInRhZyI6IiJ9; expires=Tue, 21 Nov 2023 13:47:59 GMT; Max-Age=7200; path=/; httponly; samesite=lax`

Request headers
`GET /sanctum/csrf-cookie HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: sv-SE,sv;q=0.9,en-US;q=0.8,en;q=0.7,und;q=0.6
Connection: keep-alive
Cookie: XSRF-TOKEN=eyJpdiI6IitDTzRUYmlHdG1pWm1MZUdDemc0SVE9PSIsInZhbHVlIjoidHdDWlY1UkZIWVN6Yi9qM3hoYUxSdXdJNFpNdW16VmVTOTQrTGNoVnN3Ym8xUFBvOU9tMGJiY3oxdURiRGh2QXpYd29LTlJma1c0YUxIR3lxUklEY3JxMTdHczJta1JhVktnSVQyS2VsdHN6YzM4cXZwS1hPamo5N3QvbDJsdWoiLCJtYWMiOiJlODI1MGMwNmIxNTdmZDIwNDE1MTU4NTFjZWMyNDMyZWYzYjE4NzI0OTYyYmM1YjlkYjkyZWRiMmVkM2ZlMDVkIiwidGFnIjoiIn0%3D; reuseit_core_session=eyJpdiI6Ik1MNHBTS0RsVnNVeU1FMzJGamV0M0E9PSIsInZhbHVlIjoiU3V3a3lSSzRDU0J3NVVlbUxkcFBuQUNzQnFoR29mOEQzMnRVWjJvUzhFTkxTcW5WdENzV0c1STNYN3FqejNEUi9ieE5WSGtQRTV4NDl1TGxSdmxMVUdmQkZEVTFld1lCaEZyR2x0MHducHowaGs4N2plZjhvTUdFOXQzMFdJZjYiLCJtYWMiOiJiNGE3ODdlZGI1ZTdiOGQ1MDZlNDEwNTgwOGM2ZDcyZWQ3NDYxN2JjYjA2YzliMjE5YWQ3ZjA4NzEzYTlkZGMzIiwidGFnIjoiIn0%3D; 3YbvUXEKhbfts4hD0kXysHkHDajcw6pDsaOJMzOH=eyJpdiI6InkzeTFXRVlyQU1yUGJnYjNwM1B2a0E9PSIsInZhbHVlIjoiZ1doN3I5MlFESUpLNTBXNmFlOVN3eXFiZXZXekFvMnV5QVZuSG5OOTRqVjVDZHJYbVVYbnR0akVYbnpmL2VVVmYxbXJBaFlmb0hzNnlzb05SbzU3VTVLaW5adGpqKzJHT2RUcWU2TnYxTGxmV0hnWTdtZlIzSDJyL0dWMWJBYmd1bWhaSTZtVkR2ejRHcDZWL2tRTWR2Q0szL3o0ZDUxdTlCYmtDZm9ocnMvN0tJVDRMUElhZGFKNnNGNUZmRXN6TEJHT3JoNW5Va0lFY3lPeW9TaS92NlBnNGlUN29QU2JmZTVCL2ZpWEZsZmx3V2JNN2lQaVVTcUNyRGxYYmwyUktYUFpicmpJTjQ0ZUJ0YStTaFlVWjlvYWVwbVQ1aDRpSUZQMFh1TGVTNlFPT2UvOWo4TDIyMk5nOUthU3RWUDhrY3FnM2FnYkNvUWw4dFVMdGNFRHFjaXhzRkIxK2FVb2ZHUGpzNzI0UlZRTDFTTWlXVkhldXBjaWhQZmNXcWFIelNOOFVtSGxaUTlnaDY3d2JJblNmZz09IiwibWFjIjoiM2Q1OTc1ZmU3ODMzMzUzY2Y3ZmUyN2I1OTYyMTRkNDNmZWY4YzA3NWE0OGI0MDVlMDQzY2RkN2E3MjEyMTJlZiIsInRhZyI6IiJ9
Host: 127.0.0.1:8000
Origin: http://127.0.0.1:3000
Referer: http://127.0.0.1:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
sec-ch-ua: "Brave";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"`


And the error if i console logs it is 
FetchError: [GET] "http://127.0.0.1:8000/sanctum/csrf-cookie": <no response> Failed to fetch
    at async $fetchRaw2 (ofetch.00501375.mjs:228:14)
    at async $fetch22 (ofetch.00501375.mjs:261:15)
    at async buildClientHeaders (httpFactory.mjs?v=212da25e:14:5)
    at async Object.onRequest (httpFactory.mjs?v=212da25e:56:28)
    at async $fetchRaw2 (ofetch.00501375.mjs:180:7)
    at async $fetch22 (ofetch.00501375.mjs:261:15)
    at async login (useSanctumAuth.mjs?v=212da25e:20:5)
    at async Proxy.onSubmit (Login.vue:53:3)

**Comment by martinjdlabs** [comment]
As seen on the images it says CORS error under the status in the network tab

**Comment by manchenkoff** [comment]
It's definitely on the Laravel side, but to be honest, right now I couldn't give any more details on that. Please, try to check Laravel Docs as well related to Sanctum and domains, it must be something related to domain and URL configs.

**Comment by martinjdlabs** [comment]
Okey! Thanks for the help, will try it make it work. Would really like to use this plugin

**Comment by martinjdlabs** [comment]
Okey thanks! One final question, when im deploying this later on the frontend and backend must be on the same domain? If example the laravel backend is live on one domain I cant use the laravel sanctum if my nuxt project is in local dev mode?

**Comment by manchenkoff** [comment]
You can publish it on any domains you want, even call Laravel API on the server from your local machine, but make sure that you configured all domains and sanctum parameters accordingly.

**Comment by martinjdlabs** [comment]
I managed to get rid of the CORS error now at least :) But the login function returns 419 CSRF token mismatch. Should not that function handle passing the token itself?

**Comment by manchenkoff** [comment]
Yes, before the login it requests CSRF token and passes for the authentication. It should work in both CSR and SSR modes after the latest discussion in #6, so I assume it's again some misconfiguration. Usually, it happens when Laravel recognizes nuxt client and nuxt server requests as different clients or Laravel expects different domain in `origin`/`referrer` headers.

**Comment by martinjdlabs** [comment]
If im checking the request headers I can't see any X-XSRF-TOKEN header, as Im sending when im doing it via insomnia 

POST /login HTTP/1.1
Accept-Encoding: gzip, deflate, br
Accept-Language: sv-SE,sv;q=0.9,en-US;q=0.8,en;q=0.7,und;q=0.6
Connection: keep-alive
Content-Length: 55
Host: 127.0.0.1:8000
Origin: http://localhost:3000
Referer: http://localhost:3000/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
Sec-GPC: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
accept: application/json
content-type: application/json
sec-ch-ua: "Brave";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"

**Comment by manchenkoff** [comment]
Then I assume the Laravel API didn't return it, check previous request to csrf endpoint and it's status/response headers

**Comment by martinjdlabs** [comment]
Yes you are correct I see under the set cookie it is a yellow triangle saying "This Set-Cookie was blocked because it had the "SameSite=None" attribute but did not have the "Secure" attribute, which is required in order to use "SameSite=None" and if a set SameSite=Lax I get the following  "This set-cookie was blocked because it has the samesite=lax attribute but come from cross-site response witch was not the response to top-level navigation"

**Comment by manchenkoff** [comment]
Yep, and again it's still related to Laravel config, it doesn't expect your domain or origin to be sanctum-allowed, please check the official docs to configure it according to the `origin` of the Nuxt requests - https://laravel.com/docs/10.x/sanctum#spa-configuration
