### ISSUE TITLE
[Docs] Prepare a playground environment

### ISSUE THREAD

**Issue by manchenkoff** [manchenkoff/nuxt-auth-sanctum#40]
Create a new repository with both Laravel API application and Nuxt with pre-installed `nuxt-auth-sanctum` to test different problems and provide an easy way to check assumptions from Github issues.

Also, provide a link to this repository in Issue template and Gitbook docs.

**Comment by SDIjeremy** [comment]
Is it possible to use a hosted version of Laravel or will we get CORs errors that way?
So at least every example would be working off the same source of truth Laravel which shouldn't change much anyways.

**Comment by manchenkoff** [comment]
@SDIjeremy 
Nope, it still requires the same TLD anyway for cookies handling, so the Nuxt app should be deployed into the same environment. Technically, it is possible to set up a pipeline to deploy it from a branch to update the app on the same domain, but it requires some sponsorship 😄

**Comment by manchenkoff** [comment]
Consider creating a simple app similar to Laravel Breeze for [Next.js (React)](https://github.com/laravel/breeze-next)

**Comment by manchenkoff** [comment]
Started new project similar to breeze-next - https://github.com/manchenkoff/breeze-nuxt, will update the docs for this repo once it is done

**Comment by manchenkoff** [comment]
Added a new page to the module docs. Instructions regarding backend setup will be provided in the readme of breeze-nuxt template.
