### ISSUE TITLE
bearer token not showing and not working !!! 

### ISSUE THREAD

**Issue by ismaTsmk** [manchenkoff/nuxt-auth-sanctum#41]
"Hello, it seems that the bearer token is not being added to the 'get user' request: 'http://localhost:8000/api/user'. How can I make it work? I thought the plugin would have taken care of it, which is a shame."

**Comment by jjjrmy** [comment]
> "Hello, it seems that the bearer token is not being added to the 'get user' request: 'http://localhost:8000/api/user'. How can I make it work? I thought the plugin would have taken care of it, which is a shame."

This plugin does not use Bearer Token, instead it uses the Session Cookie as per the [Sanctum SPA Authentication](https://laravel.com/docs/10.x/sanctum#spa-authentication)

**Comment by manchenkoff** [comment]
Hey @ismaTsmk, it is true and @jjjrmy is right, this module does not support token-based authentication and there is no plan for the integration any time soon. If you need to implement Bearer functionality, you can check other solutions for authentication which I mentioned in #33

**Comment by jjjrmy** [comment]
I made a PR for this #43
