### ISSUE TITLE
[Bug] Incorrect redirect on login if response is 401

### ISSUE THREAD

**Issue by munkeywolf00** [manchenkoff/nuxt-auth-sanctum#44]
#### What are the steps to reproduce this issue?
1. Create a login form
2. use login() from useSanctumAuth
3. apply the redirects: 
```
redirect: {
  keepRequestedRoute: true,
  onAuthOnly: '/login',
  onGuestOnly: '/',
  onLogin: '/',
  onLogout: '/',
},
```
4. Make the password/email/credential intentionally incorrect
-------------------------------------------
#### What happens?
- Incorrect credentials from login with 401 response code automatically redirects to onLogout route while on "onAuthOnly" route
-------------------------------------------
#### What were you expecting to happen?
- It should stay on same page during login even if credentials were wrong.
-------------------------------------------
#### Any logs, error output, etc?
- None
-------------------------------------------
#### What versions of software are you using?
- Nuxt: 3.10.3
- Vue: 3.4.19
- nuxt-auth-sanctum: 0.1.2
- Node: v20.10.0
- pnpm: 8.14.0
----------------------------------------
#### Initial Suggestion
- If this is a bug, my thought is to also check if current page is onAuthOnly so it will not redirect to onLogout
----------------------------------------

**Comment by manchenkoff** [comment]
Since 401 may be returned from any endpoint regardless of the expectation, it makes sense to check if the redirect is still valid, for instance:
- if we are on the login page, we should not redirect the user to any other page in case of 401/403 errors, but we should log/throw an exception

The same rules apply to other endpoints.
