### ISSUE TITLE
Add Feature 2FA

### ISSUE THREAD

**Issue by marsuboss** [manchenkoff/nuxt-auth-sanctum#47]
Hello,

When I enable 2FA and once logged in, the result gets: 

`{ two_factor: true }`

Is it possible to add 2FA support?

**Comment by manchenkoff** [comment]
Hey @marsuboss, can you provide more details about the 2FA you are using? which config is it - nuxt of Laravel? As far as I know, there is no default two-factor authentication in Nuxt or Laravel Sanctum.

**Comment by marsuboss** [comment]
Hello @manchenkoff,

Sorry, I forgot some details
Actually, I use Laravel Sanctum + Laravel Fortify (which allows using 2FA)

I want to obtain a variable like "two_factor" which allows me to check if the response exists an object "two_factor"
We can imagine how :
`const { login, two_factor } = useSanctumAuth()`

**Comment by manchenkoff** [comment]
@marsuboss thanks, now I see what you meant 🙂 

This module is supposed to provide functionality only for Laravel Sanctum and does not support any external features like Fortify, but if you want to return some additional values from your backend to be available on the Nuxt application side, you may want to leverage the custom user identity, more details [here](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/usage/composables/usesantumuser).

In this case, you need to extend (if it is not already) the response from your Laravel API and return `two_factor` property as a part of the user identity.

**Comment by manchenkoff** [comment]
Closed due to inactivity
