### ISSUE TITLE
API URLs for CSR/SSR with Docker containers

### ISSUE THREAD

**Issue by yuto168** [manchenkoff/nuxt-auth-sanctum#48]
Hello, I am looking for a new container for my company.
I am using docker to set up a frontend,backend container with the following configuration.

api: https://localhost:8090
nuxt3(ssr): https://localhost:3000

The nuxt config is as follows.

````
runtimeConfig: {
    public: {
      baseUrl: https://localhost:8090,.
      sanctum: {
        baseUrl: "https://localhost:8090", sanctum: {
       .....
  }, }

```

If I start up a nuxt3 local environment and run the api from localhost:3000, it succeeds, but if I run the api from the nuxt server side, it fails.
It seems that the failure is probably due to the fact that localhost is specified in the path when the api is executed from the server side.
Originally, it would be possible only with {container name}: {port} because it is accessed from a container.
However, sanctum always refers to public.sanctum.baseurl, so the path cannot be switched. I thought it would be better if I could refer to process.server, etc. in the library and change the url, etc. Is there a better solution?

**Comment by manchenkoff** [comment]
Hey @yuto168, not sure that I got it right, but if your problem is that you cannot override the `baseUrl` of the target API, then you can use environment variables to change it to `container:port` in the docker container. All configurations are available as envs, you can find more details in the [official docs](https://nuxt.com/docs/getting-started/configuration#environment-variables-and-private-tokens) and here is also [an example of the override](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/usage/configuration#environment-variables) of module config as env variable.

Let me know if you meant something different. I also use Docker for the environment but never faced any issue with routing so far.

**Comment by yuto168** [comment]
Thanks for the reply.
Sorry for my poor English.
I am able to override the environment variables with the settings described above.
So, if I call api from a client(browser) with nuxt launched on localhost:3000, the api call is successful.

The problems we are facing are
- Redirects do not work when accessing places that require authentication with an expired session.
- If you look at the logs of the frontend container, such as when reloading the screen, the api/user api is failing as shown below. This is probably due to execution on the server side(Nuxt). When I actually set up console.log, it looks like this api is failing when running on the  server side(Nuxt).

``` 
// logs of frontend container
Unable to load user identity FetchError: [GET] "http://localhost:8090/api/user": <no response> fetch failed
```

Other situations are as follows
- The following over ride sanctum environment variables in nuxt-config. (excerpts)
```
sanctum: {
    baseUrl: "http://localhost:8090", // Laravel API
    origin: "http://localhost:3000", // Nuxt app
    endpoints: {
    ....
      login: "/api/login",
      user: "/api/user",
    },
    .....
    redirect: {
      keepRequestedRoute: true, 
      onLogin: "/home",
      onLogout: "/login", 
      onAuthOnly: "/login", 
      onGuestOnly: "/", 
    },
```
- If the login method is called from a browser, for example, the api in /api/user is successful.

The redirection did not work, probably because the call to /api/user failed.
The reason why the call fails when reloading the screen is probably because localhost is specified in the server side(Nuxt).
However, if the appropriate url (container:port) to the laravel container is set to baseUrl, it fails when the api call is made from the client (browser) side.

The key question of interest is why is api℠user called on the servr side and, if so, how is the url called from the server and client separated?If so, how do we separate the url to be called from the server and the client?

If you have a docker environment with nuxt and laravel running in different containers as I do, and both client.server side api calls are successful, how are you switching the url?

Sorry if the issue is outside the scope of the library.

**Comment by manchenkoff** [comment]
Hey @yuto168, sorry for the late reply, have you tried this way in your `nuxt.config.ts`?

```typescript
export default defineNuxtConfig({
    runtimeConfig: {
        sanctum: {
            baseUrl: process.client ? 'http://localhost:3000' : 'dockerhost:port',
        },
    },
});
```

**Comment by manchenkoff** [comment]
@yuto168 
I'm closing it for now, feel free to reopen if the previous advice doesn't help

**Comment by yuto168** [comment]
@manchenkoff 
Thanks for the suggestion.
I tried this method, but in nuxt.config I can reference 'process', but 'process.client'(server) always returns undefined.
I checked 'process' with log in nuxt.config and could not find any parameters for process.client.
