### ISSUE TITLE
Preventing redirection after login

### ISSUE THREAD

**Issue by WanyoikeJ** [manchenkoff/nuxt-auth-sanctum#50]
Hello @manchenkoff,

Ho do i prevent redirection after a successful login. am hopping to do this so that i can look at my local-storage or cache if there is intended page so that i can take the user there or even some instances where the login function is in a popup hence i just need to reload the same page they are looking at.

**Comment by jjjrmy** [comment]
probably you can change the redirect after login url by changing the config dynamically?
but already this supports the feature of redirecting to intended page by a url parameter.

**Comment by manchenkoff** [comment]
Hey @jjjrmy, when `login` method is completed successfully the module checks `sanctum.redirect.login` value in the configuration and uses it for the redirect. If you want to prevent it, you can just set it to false like this

```typescript
export default defineNuxtConfig({
    sanctum: {
        redirect: {
            onLogin: false,
        },
    },
});
```

For more details, you can check [the docs](https://manchenkoff.gitbook.io/nuxt-auth-sanctum/usage/configuration)

**Comment by WanyoikeJ** [comment]
Thanks so much, i dint know that the configs can take boolean too if you dont need them to be triggered.
