### ISSUE TITLE
[Help Needed] Unable to load user identity [GET] "http://localhost:8000/api/user"

### ISSUE THREAD

**Issue by norjamille-kasan** [manchenkoff/nuxt-auth-sanctum#66]
Unable to load user identity [GET] "http://localhost:8000/api/user": <no response> fetch failed

I have the same issue on [this](https://github.com/manchenkoff/nuxt-auth-sanctum/issues/57)
except I'm not using docker. I'm just running my laravel (v11) app on http://localhost:8000 and my nuxt app at http://localhost:3000

I already did some of the fixes that was said [here](https://github.com/manchenkoff/nuxt-auth-sanctum/issues/57) but the error in the console is still showing.

I really need some help :(. thanks a lot

APP_URL=http://locahost:8000
SESSION_DOMAIN=localhost
SANCTUM_STATEFUL_DOMAINS=localhost:3000
FRONTEND_URL=http://localhost:3000

` devServer: {
        host: "localhost",
    },
    runtimeConfig: {
        public: {
            sanctum: {
                origin: "http://localhost:3000",
            },
        },
    },
    sanctum: {
        baseUrl: "http://localhost:8000", 
        origin: "http://localhost:3000",
        endpoints: {
            csrf: "/sanctum/csrf-cookie", 
            login: "/api/login",
            logout: "/api/logout", 
            user: "/api/user",
        },
        redirect: {
            keepRequestedRoute: true,
            onLogin: "/",
            onLogout: "/",
            onAuthOnly: "/sign-in",
            onGuestOnly: "/",
        },
    },`

**Comment by norjamille-kasan** [comment]
wrong label.

**Comment by manchenkoff** [comment]
Duplicate of #67
