### ISSUE TITLE
Redirect if the state was a 401 response

### ISSUE THREAD

**Issue by swarakaka** [manchenkoff/nuxt-auth-sanctum#7]
Hello @manchenkoff , 
i suggest to check the response status, if the code is 401 it will execute the logout action.

**Comment by manchenkoff** [comment]
Hey @swarakaka, thanks for the idea! Could you provide some use case for that scenario? 

I would imagine that most of the cases should be covered either with middleware or with 403 response from the API. Calling logout when you get 401 sounds to me more like a hack than proper error handling 😄 also it might cause misbehaving of the application if you don't have control on the authentication flow

**Comment by swarakaka** [comment]
Hi @manchenkoff, thanks for your quick reply.
When the user logs in to the application, the session remains in the backend for a certain period of time, for example, 60 minutes. The session has expired and the user is still in the application(frontend) changing routes but not responding correctly. Unless the programmer breaks this in all these requests, this is a lot of work, especially if the application is large. However, if the (client) method is checked for errors, especially 401 error (which Laravel has set according to the standard for Unauthorized) - if the status code is that error, the user should be logged out of the frontend and requested to log in again.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401

**Comment by manchenkoff** [comment]
Oh, true, it might work like that if you do not refresh the page for a long time which apparently does not trigger the identify refresh. I completely missed that case, thanks 😄 I will open PR with a fix.

**Comment by manchenkoff** [comment]
@swarakaka published as `v0.0.12`, feel free to re-open this issue if the problem persists
