### ISSUE TITLE
Use $fetch to handle requests to api from inside a function where we should not use useAsyncData

### ISSUE THREAD

**Issue by andyjamesn** [manchenkoff/nuxt-auth-sanctum#89]
I have been unable to get my requests to work when using `useFetch` I get a `CSRF token mismatch` error.

Then I found `useSanctumClient` in your docs. Using this things started to work. 

But I am using this with PUT and DELETE methods called by a button within a function

According to Nuxt useFetch and useAsyncData as used on the `useSanctumClient` code example should not be called outside of setup and the Vue context like a delete function. 

https://github.com/nuxt/nuxt/discussions/25602

Also Nuxt adds a warning in the console to use $fetch instead. 

![CleanShot 2024-05-07 at 02 21 21@2x](https://github.com/manchenkoff/nuxt-auth-sanctum/assets/54320410/f5dbccfe-fdd9-4f29-a294-dfc782b494b6)

**Comment by manchenkoff** [comment]
Hey @andyjamesn, could you please provide a code example that triggers this error?

Composable `useSanctumClient` returns an instance of `$fetch`, so you can use it directly without using `useAsyncData` like

```typescript
const sanctumFetch = useSanctumClient()

// keeps auto mapping into ResponseDto
const responseObject = sanctumFetch<ResponseDto>('/api/endpoint', {method: 'PUT'})
// returns raw response, so you can access status code, headers, etc
const responseRaw = sanctumFetch.raw('/api/endpoint', {method: 'DELETE'})
```

**Comment by andyjamesn** [comment]
Thanks, I figured this out but I was working on my delete method which was failing with a `fetch failed` so thought I was still doing something wrong. 

As it turns out this was a known DELETE empty body issue in unjs or ofetch based on this thread. 

https://github.com/unjs/h3/issues/375

I upgraded to 20.11 and it solved the issue. 

Thanks for the help, this can be closed now.
