### ISSUE TITLE
Middlewares

### ISSUE THREAD

**Issue by martinjdlabs** [manchenkoff/nuxt-auth-sanctum#9]
How do I use the middlewares in my pages? If I would like to use the sanctum:auth on a logged in only page?

**Comment by manchenkoff** [comment]
Hey @martinjdlabs to apply the middleware in Nuxt you should use the following example:

```vue
<script setup lang="ts">
definePageMeta({
  middleware: ["sanctum:auth"]
})
</script>
```

Here is an example which I created for a playground in this repo - [profile page](https://github.com/manchenkoff/nuxt-auth-sanctum/blob/main/playground/pages/profile.vue).

This should be defined in the page you want to make available for authenticated users only. More details about usage of middleware you can find in the docs - [Nuxt 3 Middlewares](https://nuxt.com/docs/guide/directory-structure/middleware)
